sysdiglabs/sysdig-sdk-python

- .travis.yml
- README.md
@jsrodman pointed out that the manual command line in the README didn't have the intended effect. I've seen the `setup.py` approach as a typical approach for installing with a local checkout. @jsrodman pointed out that `pip -e` is another option, but they both seem to land in the same place (particularly if they're using virtualenv as we suggest). @davideschiera, any opinions? If you're ok with what's here, feel free to merge.
> Correct the manual install command line

- sdcclient/_client.py
Add methods to manage auto-updating falco rules. These are mostly useful
internally if we decide to push out new rules updates to customers.
> Add methods to manage auto-update falco rules.

- README.md
- sdcclient/_client.py
https://github.com/draios/python-sdc-client/pull/15 added support for skipping SSL certification verification for the benefit of [On-Premises installs](https://support.sysdigcloud.com/hc/en-us/articles/206519903-On-Premises-Installation-Guide), but the docs were not updated. This adds the docs for that, as well as general class docs that were missing that covered the ability to set a URL for On-Prem as well.
cc: @adityakinifr
> Document steps for connecting in On-Premises installs

- .travis.yml
- sdcclient/_client.py
Issue https://github.com/draios/python-sdc-client/issues/17 pointed out that `get_notification_ids()` was not prepared to find OpsGenie Notification Channels. This PR adds support for that. Tested it out by using `examples/create_alert.py` with `notify_channels = [ {'type': 'OPSGENIE', 'name': 'Cloud Platform OpsGenie'} ]` and it now found & created the Alert successfully with my OpsGenie channel.
cc: @adityakinifr @davideschiera
> Add support for getting IDs of OpsGenie Notification Channels

- examples/create_alert.py
- sdcclient/_client.py
Added support for Webhook Notification Channels, as alerted in issue https://github.com/draios/python-sdc-client/issues/22.
Also noticed one of the automated tests was failing because it was pointing at an Email Notificaiton Channel with a personal email address that no longer existed in the test demo-kube environment. I fixed this by pointing to a channel with test addresses that still exists.
> Add support for Webhook Notification Channels when creating Alerts

- sdcclient/_client.py
https://github.com/draios/python-sdc-client/issues/24 alerted us to the fact that `create_alert()` was failing if two Alerts were created with the same description. The UI allows this and the API works fine if we just remove the offending code, so I've done that here. I've run it by @ldegio on Slack who wrote the original code and he's :+1: on the change, so I'm gonna go ahead and merge it.
> create_alert with duplicate descriptions should be permitted

- .travis.yml
- examples/update_alert.py
- sdcclient/_client.py
https://github.com/draios/python-sdc-client/issues/26 called out the need for an `update_alert()` function. This PR adds the new function and an example to be run as an automated test. The automated test has passed in Travis on the branch, and includes the three types of alert modifications suggested by the end user.
> Add update_alert()

- examples/list_alerts.py
- examples/restore_alerts.py
- examples/restore_dashboards.py
- sdcclient/_client.py
- setup.py
https://github.com/draios/python-sdc-client/issues/27 identified a desire to be able to create Alerts using full JSON objects in a file as opposed to the current `create_alert()` which requires specifying the separate Alert details in the call to the Python method. This PR tries to kill two birds with one stone by extending the `list_alerts.py` example to dump the full set of Alerts to a JSON file, and adds a new `restore_alerts.py` example that reads them back in from such a file. Now we have backup/restore examples, and at the same time someone could use the "restore" example to create wholly new Alerts as long as they follow the right JSON format.
> Alerts create/backup/restore with JSON file

- .travis.yml
- examples/restore_alerts.py
Recent issues have identified the need for the `update_alert()` function and also the ability to do a bulk creation of Alerts using a JSON file (the latter being accomplished via the new `restore_alerts.py` example.) In a recent update to https://github.com/draios/python-sdc-client/issues/26, a user identified that it would be useful to do bulk updates as well, such as to sync from a golden set maintained in a JSON file. This PR updates `restore_alerts.py` to cover this case as well.
> Enhance "restore alerts" example to include updates (previously was only creates)

- .travis.yml
- examples/delete_event.py
After merging an unrelated enhancement, the Travis run showed the `delete_event` example failed. I traced it down to an event in the backend that's failing delete reasons yet to be explained (event ID=413658984227033090). However, it was an event that shouldn't have been flagged by `delete_event` in the first place. That is, the `post_event` examples were creating events with names "test event name" and `delete_event` was targeting all events with name "test event". However, I think due to the way ES search works, this was actually matching all items with names matching test OR event, which is why it was finding this rogue/unrelated event that wouldn't delete. I've now tightened all of this up by using underscores to make single-token names "test_event_name", so that way the examples will …
> Fix tests for events

- examples/restore_dashboards.py
When doing some Dashboard backup/restore recently, I found that this example had not been made hip to the recently-added ability to set scope (via `filterExpression ` parameter) in Dashboards. This  PR handles that.
I just tested it out ok myself and automation has passed. Since it's such a small change I'm going to go ahead and merge.
> Include filterExpression (scope) when restoring backed-up Dashboards

- examples/get_agents_config.py
- examples/set_agents_config.py
- examples/user_team_mgmt.py
set_agents_config.py/get_agents_config.py currently read and write the
raw json that's inside the api body. This isn't very user friendly.
Change them to work directly with the agent config-as-yaml content
instead. get_agents_config.py will extract the yaml confg from the json
response and print it. set_agents_config.py will take the agent config
from the file on the command line, verify that it can be parsed as yaml,
wrap it in json, and PUT it.
> Use yaml for agent config content

- .travis.yml
- examples/list_users.py
- sdcclient/_client.py
A customer expressed a need to be able to list all users in an environment, so I put together this new function and example. The automation passes in Travis, and the customer tested the branch and gave it a 👍
> New "get_users" function and corresponding example/automation

- README.md
- sdcclient/__init__.py
- sdcclient/_client.py
For consistency with SdSecureClient
> Renaming SdMonClient -> SdMonitorClient

- examples/user_team_mgmt.py
Previously, `examples/user_team_mgmt.py` was passing ok even though the customer account it points to had reached its max Teams count. I've changed the example to genuinely fail with a proper exit code in these situations, and also have increased the Teams count on the relevant customer account so it should pass legit. While I was at it, I made it fail in more of the other cases as well, since as long as the test environment is healthy (e.g. Team of the same name was properly deleted at the end of any prior test) it should always pass.
> Make User/Team Management example fail more often

- sdcclient/_client.py
The UI is using sampling for aggregating several events,  and I would like to keep this consistency when using the API.
I have added a sampling parameter to context, and I use its value for building the URL.
Thanks!
> Add sampling support for get_policy_events_* methods

- doc/index.rst
Well, this is embarrassing. :)  It looks like a typo in the Sphinx config has made it such that the docs for Monitor-specific functions have not been getting generated since October, 2017:
```
Running Sphinx v1.3.6
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] index
/home/phil/python-sdc-client/doc/index.rst:19: WARNING: autodoc: failed to import class u'SdMonClient' from module u'sdcclient'; the following exception was raised:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 393, in import_object
obj = self.get_attr(obj, part)
File …
```
> Restore Sphinx auto-creation of Monitor function docs

- sdcclient/_client.py
https://github.com/draios/python-sdc-client/issues/53 points out that the `switch_user_team()` method doesn't work as described and should be deleted. This method is also not referenced in the `examples` nor automated `tests`.
I did some searching and confirmed that this method was basically DOA. It first appeared in https://github.com/draios/python-sdc-client/commit/9f7d3cf7eb88951250727c4df275a744a6bb659d on November 3, 2016, which was part of a series of commits to add Teams functionality to create https://github.com/draios/sysdig-kube-watcher. However, the `switch_user_team()` method was never used by Kubewatcher, and indeed, in Kubewatcher commit https://github.com/draios/sysdig-kube-watcher/blob/d1cb4eb33ab5214994c5a3924485c29511504070/main.py#L207 on November 5, 2016, the approach …
> Remove switch_user_team() method, as it never worked and can't work as described

- examples/restore_alerts.py
- sdcclient/_client.py
Someone might be restoring Alert configs from another environment, in which case the Notification Channel IDs in the saved Alert JSON is not expected to match the Notification Channel IDs in the target environment. This enhancement drops the non-matching IDs but still restores the Alert config.
To support this, the `get_notification_ids()` method is enhanced such that if no `channels` filter is provided, it just lists all IDs. It used to only support returning a filtered list based on type/name of channels.
> SMPROD-1309: Example for restoring Alerts now removes non-existent notification channel IDs

- examples/add_users_to_secure.py
SMPROD-1326 highlights a limitation we have at the moment with the Secure Operations team. Users created in Monitor via the API (such as those created as a side-effect of the LDAP Mapping feature that's currently in beta) land in the default team for Monitor. But granting them access to Secure would typically require an Admin to add them to the Secure Operations team in the Secure UI as a separate step. While waiting on a more elegant option, users who effectively want all such Monitor users to also land in Secure could instead run this example in a cron job. That way any users recently auto-created on the Monitor side (once again, such as via LDAP Mapping) could be auto-added to Secure Operations as well.
@aponjavic: I put you down as a Reviewer because I want to double check my …
> SMPROD-1326: Example to add all users to Secure Operations team

- sdcclient/_client.py
When issuing a `edit_user` using a `ROLE_CUSTOMER` credentials against a user from the same account, `enabled` field needs to be preserved.
> Preserve enabled user attribute when editing

- sdcclient/_client.py
Victorops was left out as a valid type, but appears in the REST API output.
> Add VICTOROPS to valid notification channel types

- examples/restore_dashboards.py
@harrysx had a use case where he'd taken a ZIP of dashboards originally created from `download_dashboards.py`, unzipped it to trim it down to a subset, then re-zipped it. The `restore_dashboards.py` script ultimately choked on this with the error:
```
Traceback (most recent call last):
File "restore_dashboards.py", line 42, in <module>
j = json.loads(data)
File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
The contents of the repackaged ZIP:
```
Archive: …
```
> Catch exception for non-JSON items in Dashboard ZIP

- sdcclient/_client.py
`agentInstallParams` is no returned anymore at GET `api/users` and it would be ignored as part of the PUT request
This was currently failing at our staging environment. We should schedule the release of this patch among the backend release to saas.
> Remove unused parameter

- sdcclient/_client.py
1. Scope is expected to be a string (no longer an object)
2. Public sharing is disabled
3. Old grouping configuration and scope support removed
4. Patch dashboard format to fix UI custom scope warning
> Fix dashboard create (copy, from file)

- examples/flip_alerts_enabled.py
Cloned the 'update_alerts.py' example to create a script that would take a list of alerts, and flip their enabled status. A customer had requested the ability to selectively enable / disable a list of alerts on a schedule, so I created this so they could run it on a cronjob. Will also add this as a FR.
> Created a script to enable/disable a list of alerts

- sdcclient/_client.py
Add `public` optional parameter to define whether a new dashboard should be publicly shared or not. Affected functions:
- `create_dashboard_from_template`
- `create_dashboard_from_view`
- `create_dashboard_from_dashboard`
- `create_dashboard_from_file`
> Add parameter to control public sharing option

- sdcclient/_secure.py
Got dropped as a part of the secure/monitor split in https://github.com/draios/python-sdc-client/pull/74
> Add missing import

- sdcclient/_common.py
- sdcclient/_monitor.py
- sdcclient/_scanning.py
- sdcclient/_secure.py
As well as adding support to fetch policy events by id.
> Add support for Sysdig Secure compliance tasks

- examples/add_notification_email.py
- examples/add_users_to_secure.py
- examples/dashboard_save_load.py
- examples/download_dashboards.py
- examples/flip_alerts_enabled.py
- examples/get_agents_config.py
- examples/get_secure_default_falco_rules_files.py
- examples/list_admins.py
- examples/print_conn_table.py
- examples/restore_alerts.py
- examples/restore_dashboards.py
- examples/set_agents_config.py
- examples/set_explore_group_configuration.py
- examples/set_policy_order.py
- examples/set_secure_default_falco_rules_files.py
- examples/user_team_mgmt.py
- examples/user_team_mgmt_extended.py
So all comply with the 'ok, res = sd*client' form.
> Clean up the rest of the examples

- sdcclient/_secure.py
~~And clean up the rest of the examples.~~
> Add support for secure commands audit

- .travis.yml
- test/start_agent.sh
- test/stop_agent.sh
- test/test_monitor_apis.sh
- test/test_secure_apis.sh
1. Use a single command line to launch Sysdig agent container
2. Wait longer after the launch, to make data is made available via Sysdig API
3. Simplify test for policy events (wait longer instead of polling)
> Consolidate and simplify tests using Sysdig agent

- sdcclient/_secure.py
To add the metrics param we need also to have from and to params in the
API call. I'm adding default from/to params if needed.
> Add metrics to the commands audit

- examples/dashboard_backup_v1_restore_v2.py
- sdcclient/_common.py
- sdcclient/_monitor.py
- sdcclient/_monitor_v1.py
Use case: You created a dashboard backup with dashboards API v1. You now have the Sysdig API with dashboards v2. The Python library will convert the v1 dashboard to the v2 format.
> Allow dashboards created with API v1 to be uploaded to API v2

- examples/list_profiles.py
- sdcclient/_secure.py
Add API helpers for retrieving information about Image profile.
Features:
1. Get a list of all image profiles in the scope
2. Get profile details by passing a (partial) profile ID
Others:
- Partial profile ID support
- Profile ID collision detection
> Get image profiles from secure

- .travis.yml
- examples/get_anchore_users_account.py
- requirements.txt
- sdcclient/_scanning.py
- setup.py
**Usage**
**Anchore User Account** 
```
from sdcclient._scanning import SdScanningClient
client = SdScanningClient('<token>', 'http://localhost:9040')
print(client.get_anchore_users_account())
[True, {'created_at': '2019-08-12T23:41:58Z', 'email': None, 'last_updated': '2019-08-12T23:41:58Z', 'name': 'tenant_1PLVMqZvrKDcMVRDTDtUL4dOki4', 'state': 'enabled', 'type': 'user'}]
```
This PR implements import_image and accounts API needed to do inline-scanning. Currently it is in a bash script here https://github.com/sysdiglabs/secure-inline-scan/blob/inline-scan/inline_scan.sh#L463
**Import Image**
```
from sdcclient._scanning import SdScanningClient
client = SdScanningClient('<token>', 'http://localhost:9040')
print(client.get_anchore_users_account())
[True, {'created_at': …
```
> SSPROD-2210: Added import_image and anchore_account to SDC CLI

- test/test_secure_apis.sh
Fixing v1 v2 policy response checks.
This PR is meant to keep the test_secure_api bash script generic between the new formats in policy/v2 and policy/v1.
> Fixing v1 - v2 policy response checks

- sdcclient/_scanning.py
- setup.py
Removing digest based scan result call
> Removing digest based scan result call

- sdcclient/_scanning.py
Use the Sysdig endpoint by default, which is asynchronous, to
avoid timeouts.
> Add support for importing images asynchronously

- sdcclient/_common.py
Extra / characters in the URL will deal to errors according to CNATIVE-1260
> fix: Strip / characters from the URL

- sdcclient/_secure.py
When we create a macro or a list we may need to specify if this is an append to other existing macros or rules.
> fix: Add append field to falco macro and list creation

- sdcclient/_secure.py
Signed-off-by: kaizhe <derek0405@gmail.com>
Before the changes:
```
+ python src/deploy_falco_rules.py --host https://secure-xxxx.sysdig.com --user **** --password **** --python-sdc-dir sysdig-sdk-python
Backend supports falco rules files, also deploying falco rules files...
Could not set system rules file (b"Loading falco rules files from ./rules_files...\nCould not read content at ./rules_files/0.8.2/falco_rules.yaml/0/content: '<' not supported between instances of 'str' and 'int'\n"
```
> fix falco rule version comparison

- sdcclient/_scanning.py
- specs/secure/scanning_vulnerability_exceptions_spec.py
- specs/secure/scanning_vulnerability_spec.py
New methods for the SdScanningClient:
- add_vulnerability_exception_bundle
- delete_vulnerability_exception_bundle
- list_vulnerability_exception_bundles
- get_vulnerability_exception_bundle
- add_vulnerability_exception
- delete_vulnerability_exception
- update_vulnerability_exception
> feat: Add vulnerability exception methods

- .github/workflows/codeql-analysis.yml
This PR adds a GitHub Code Scan workflow to Git Hub actions for the repository, to look for vulnerabilities in the code and libraries used, with the following characteristics:
* It will scan the repository for vulnerabilities periodically (in case the vulnerability db updates with new ones), each Friday at 6:00 AM.
* It will trigger on push or pull requests to master
* It will scan Python language files (autodetected supported programming language)
* It is non blocking, meaning that a detection will not block the pipeline
* Security alerts can be checked at: https://github.com/sysdiglabs/sysdig-sdk-python/security/code-scanning
> ci: Added GH Code Scan action

- examples/restore_alerts.py
Each time you restore alerts "updated via restore_alerts.py" in the description is appended so you get something like: "${DESCRITPION} updated via restore_alerts.py updated via restore_alerts.py updated via restore_alerts.py". 
This PR removes this part so the description doesn't grow anymore.
Fixes #135
> fix(examples): Do not append 'updated via' in restore_alerts example

- Pipfile
- Pipfile.lock
- setup.py
This PR relaxes dependencies, not pinning them to a specific version, so they can work with newer versions, and requiring `requests>=2.23, urllib3>=1.25.8` instead of `requests==2.24, urllib3==1.25.10`
> chore: Relax dependencies for installation

- sdcclient/monitor/_dashboards_v3.py
- specs/monitor/dashboards_v3_spec.py
The previous version of the get_dashboards method was only able to retrieve partial information from the dashboards. The current one allows to disable the "light" mode.
> feat: get_dashboards now can retrieve full information

- README.md
- sdcclient/monitor/dashboard_converters/_dashboard_scope.py
- specs/monitor/dashboard_converters/dashboard_scope_spec.py
The installation instructions are deprecated in the README, this PR fixes this.
> docs: Update README with installtion instructions

- sdcclient/_common.py
- sdcclient/_monitor.py
- sdcclient/_monitor_v1.py
- sdcclient/_scanning.py
- sdcclient/_secure.py
- sdcclient/_secure_v1.py
- sdcclient/ibm_auth_helper.py
- sdcclient/monitor/_dashboards_v2.py
- sdcclient/monitor/_dashboards_v3.py
- sdcclient/monitor/_events_v1.py
- sdcclient/monitor/_events_v2.py
- sdcclient/secure/_policy_events_old.py
- sdcclient/secure/_policy_events_v1.py
This PR implements retries in the Python SDK.
> feat: Add retry strategy with backoff of 0.5s

- test/test_secure_apis.sh
The `set_secure_system_falco_rules.py` must fail because it's only allowed to set up the system falco rules in an on-prem installation. The script was looking for the string "Access is denied: Not enough privileges to complete the action" but since #159  the errors are using a retry strategy, and after 3 failure attempts, raise an exception instead of returning an error.
This PR removes the part that checks for the string since the new output is empty.
> fix(ci): Update scheduled test that fails due to retries

- sdcclient/ibm_auth_helper.py
The change on #159 made a regression on the IBM Auth Helper.
This PR fixes this.
Closes #164
> fix: Referenced self on static method on IBM Auth Helper

- sdcclient/_scanning.py
- specs/secure/scanning/policy_evaluation_spec.py
This method will allow to retrieve the scanning results for all the policies, or just the specified one.
> feat: Add get_image_scanning_results method to SdScanningClient

- examples/download_dashboards.py
- sdcclient/monitor/_dashboards_v3.py
This PR updates the `download_dashboards.py` example to retrieve all the information from dashboards and updates the documentation of the `get_dashboards` method.
> docs: Update download_dashboards example and get_dashboards documentation

- examples/get_secure_policy_events.py
- sdcclient/_monitor.py
- sdcclient/secure/_policy_events_v1.py
Pagination in the Secure API doesn't honor the first API call, thus ignoring the duration specified in the parameters. This workaround increases the number of policies that can be retrieved in a single API call, and removes the pagination from the example.
> fix: Increase limit to retrieve policy events without pagination

- sdcclient/_common.py
Default role and entry point are resetting by sdclient.edit_team method
When customer calls sdcclient.remove_memberships (that calls edit_team)
two team attributes are resetting:default team, entry point
> SMBACK-6098 copy old values for defaultTeamRole and entryPoint

- sdcclient/_common.py
```
site-packages/sdcclient/_common.py:11: DeprecationWarning: Using 'method_whitelist' with Retry is deprecated and will be removed in v2.0. Use 'allowed_methods' instead
```
> Fix `retry` warning

- sdcclient/_secure.py
- sdcclient/secure/__init__.py
- sdcclient/secure/_activity_audit_v1.py
- specs/secure/activitylog_v1_spec.py
- specs/secure/scanning/policy_evaluation_spec.py
- specs/secure/scanning/query_image_content_spec.py
Creates a new ActivityAuditClientV1 to query the new Activity Audit events. This deprecates the old Command Audit Log.
> feat: New ActivityAuditClientV1 to query Activity Audit events

- poetry.lock
- pyproject.toml
For versions lower than 1.26.0, this error arises:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.9/dist-packages/sdcclient/_monitor.py", line 11, in __init__
super(SdMonitorClient, self).__init__(token, sdc_url, ssl_verify, custom_headers)
File "/usr/local/lib/python3.9/dist-packages/sdcclient/monitor/_dashboards_v3.py", line 14, in __init__
super(DashboardsClientV3, self).__init__(token, sdc_url, ssl_verify, custom_headers)
File "/usr/local/lib/python3.9/dist-packages/sdcclient/monitor/_events_v2.py", line 9, in __init__
super().__init__(token, sdc_url, ssl_verify, custom_headers)
File "/usr/local/lib/python3.9/dist-packages/sdcclient/_common.py", line 55, in __init__
adapter = SysdigHTTPAdapter(ssl_verify=self.ssl_verify)
File …
```
> chore: Require minimum urllib3 1.26.0 version

- sdcclient/secure/_activity_audit_v1.py
- specs/secure/activitylog_v1_spec.py
When trying list_events() with following parameters:
```
to_date = datetime.datetime.utcnow() 
from_date = to_date - datetime.timedelta(seconds=40)
```
I have found that I retrieve events from 2 hours ago. Note: That my country is now UTC+2
utcnow() returns a datetime without timezone:
```
bool(datetime.datetime.utcnow().tzinfo)
>>>False
```
And so when applying timestamp to it, then Python assumes your localtime, and so the 2 hours difference
So using now(), that provides the localtime, fixes the previous issue 
Thanks @marojor for suggesting the fix 
Tested using a real sysdig customer:
1) Generating activity audit events
2) And then trying to retrieve the events with this API
> fix: Solve timezone issue in ActivityAuditClientV1

- sdcclient/_common.py
adding rapid response permissions to team create and team edit
> Update python script to support rapid response

- sdcclient/_common.py
> [SP-748] Fix get_team method in sdccli python lib

- sdcclient/_common.py
We don't need to retry  when we get a `Bad request` response.
> fix: do not retry on bad requests

- examples/create_access_keys.py
- examples/update_access_keys.py
- sdcclient/_common.py
This PR allows to pass Team ID, number of reserved agents and agent limits to be passed to `create_access_key` and introduce `update_access_key` as per API docs:
https://docs.sysdig.com/en/docs/developer-tools/sysdig-api/managing-access-keys/#create-an-access-key
> feat(access_key): Implement teamId in create_access_key and implement update_access_key

- sdcclient/_common.py
I have seen a failure trying to create a capture due to: 
This PR protects the use of hostName key from agent dictionary
> Fix exception in case no hostname label is available

- pyproject.toml
Currently sphinx-rtd-theme is incorrectly being included in the main group dependencies and hence pulls in itself and sphinx as a runtime dep for the client. Declaring it in the docs group ensures it is only installed if the `sdcclient[docs]` is installed.
Not only does this pull in a number of unnecessary dependencies, it also forces a backlevel urllib3 1.x to be used. Here's the before and after this PR of a `pip install sdcclient` into an empty venv:
```diff
@@ -1,29 +1,12 @@
Package                       Version
----------------------------- --------
-alabaster                     0.7.16
-babel                         2.15.0
certifi                       2024.6.2
charset-normalizer            3.3.2
-docutils                      0.17.1
idna                          3.7
-imagesize …
```
> fix: declare sphinx-rtd-theme in docs extras
