sdcclient/_client.py

@davideschiera could you please take a look and merge if it looks good.

Add option to disable SSL certificate verification

---

README.md
requirements.txt
test/test_secure_apis.sh

pyyaml now used for secure example files

Add missing dependency

---

sdcclient/_client.py

Currently, the sdc-client is not fully compatible with Python 3 and whenever you try to use it with this version, it crashes.
This changes should work in Python 3 while maintaining **backward compatibility** with Python 2 until it's support is removed.

Make sdcclient fully compatible with Python 3

---

sdcclient/_scanning.py

Exception is thrown when trying parse Scanning Policy - TypeError: cannot unpack non-iterable NoneType object.

Fix error while getting scanning policy

---

sdcclient/_secure.py

When reading/writing default rules files from disk, also look for a file
"default_policies.yaml" alongside the tag directory and include it in
the call to defaultRulesFiles.
Still need to test with a backend that has the required changes.

Add default policies to default rules files

---

examples/get_pdf_report.py
sdcclient/_scanning.py

Downloads a pdf with a full report of an image in a certain date.

Add scanning pdf_report method

---

examples/get_image_info_by_id.py
examples/get_image_present_in_list.py
examples/get_image_scan_result_by_id.py
sdcclient/_scanning.py
test/test_secure_apis.sh

SSPROD-2436 :  add get scan result
Usage
GET Image Scan Result
```
from sdcclient._scanning import SdScanningClient
client = SdScanningClient('<token>', 'http://localhost:9040')
image_id = '965ea09ff2ebd2b9eeec88cd822ce156f6674c7e99be082c7efac3c62f3ff652'
full_tag_name = 'docker.io/alpine:3.10'
print(client.get_image_scan_result_by_id(image_id, full_tag_name))
[True, [{'sha256:965ea09ff2ebd2b9eeec88cd822ce156f6674c7e99be082c7efac3c62f3ff652': {'docker.io/alpine:3.10': [{'detail': {}, 'last_evaluation': '2019-10-28T22:17:19Z', 'policyId': 'default', 'status': 'pass'}]}}]]
```
This PR implements GET image scan result API needed to do inline-scanning. Currently it is in a bash script here https://github.com/sysdiglabs/secure-inline-scan/blob/inline-scan/inline_scan.sh#L463
Also adding GET …

SSPROD-2436 :  add get scan result

---

sdcclient/_scanning.py

Setting it to async method

---

sdcclient/_secure.py

From `/api/profiling/v1/secure` to `/api/v1/profiling`
reference: https://github.com/draios/secure-backend/pull/350

Fix profiling endpoint

---

examples/get_image_scan_result_by_id.py
examples/get_latest_pdf_report_by_digest.py
sdcclient/_scanning.py

Adding method for fetching latest pdf report with image digest

Adding method for fetching latest pdf report with image digest

---

sdcclient/_scanning.py
setup.py

Changing to scanning accounts endpoint

Changing to scanning accounts endpoint

---

sdcclient/_scanning.py

Add a new method to list whitelisted CVEs, required by sdc-cli to include the whitelisted column in cve-report

Add list_whitelisted_cves method

---

Pipfile
Pipfile.lock
examples/list_events.py
sdcclient/_common.py
sdcclient/_secure.py
specs/_common/event_spec.py

This PR makes the event retrieval to use the v2 of the API.
Also adds tests with `mamba` and implements the use of `Pipfile` for reproducible builds.

fix: List events was not using v2 API -- SSPROD-2987

---

examples/list_alert_notifications.py

The example list_alert_notifications.py is incorrect, this PR solves it.

fix(examples): Updating a map returns null

---

examples/list_access_keys.py
sdcclient/_common.py

list, create, disable and enable access keys
https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Sysdig-access_key

Add support for access keys

---

examples/list_access_keys.py
sdcclient/_common.py

List, create, disable and enable access keys

feat: Add support for access keys

---

sdcclient/_secure.py

Duplicates https://github.com/sysdiglabs/sysdig-sdk-python/pull/118 to master.

fix: Add append field to falco macro and list creation

---

examples/create-update_dashboard_from_file.py

@davideschiera this is the script we discussed yesterday on Slack

Example of dashboard update from a json file

---

.flake8

This PR adds configuration for the Flake8 linter

ci: Add Flake8 linter configuration

---

.github/workflows/release.yml

This PR adds an automated way to release the Sysdig SDK for Python.

cd: Add automated release process

---

sdcclient/_scanning.py
specs/secure/scanning_vulnerability_spec.py

This PR adds the `get_vulnerability_details` method for the SdScanningClient

feat: Add vulnerability details endpoint

---

examples/get_secure_user_falco_rules.py
fixtures/custom_rules.yaml
sdcclient/_secure.py
specs/secure/custom_rules_spec.py
test/test_secure_apis.sh

This PR fixes the retrieval and set-up of custom rules in the new API endpoint.

fix: Custom rules

---

sdcclient/_secure.py

The current implementation uses the first file, which may not be the same as the API expect for user-defined rules, which is the one called `falco_rules_local.yaml`.

fix: Use falco_rules_local.yaml as user rules file instead of the first

---

README.md

`httplib` has been replace by `http.client`

Update code to Python 3
